#pragma once

#include <memory>

#include "node_system/graph.h"

// GS9: programmatic builders for the committed Language/tests/nodegen/
// .celg fixtures. Building via NodeTypeRegistry::AddRegisteredNode +
// Graph::Connect (rather than hand-authoring .celg text directly) means
// every wire is validated at construction time -- Connect rejects a
// type mismatch or wrong pin direction immediately, which hand-typed
// pin/connection lines can't. `celc --dump-nodegen-fixture <name>`
// prints SerializeGraph(*Build...()) so a fixture can be regenerated
// the same way if the node catalog's pin shapes ever change.
namespace ce::lang::tools {

// The GS9 flagship end-to-end verification graph: an entity that starts
// at the origin and bounces back and forth along X between 0 and 5,
// exercising OnStart/OnTick/Sequence/While/Branch/CompareLt/CompareGe/
// Add/Mul/MakeVec3/SetPosition/Spawn/Destroy/Log/SetVariable/
// GetVariable -- 16 of the 20 catalog types, run through the real JIT
// via celc --run-graph and diffed against a hand-written .cel
// describing the identical behavior (see
// Language/tests/nodegen/run_nodegen_parity_test.cmake).
std::unique_ptr<ce::node_system::Graph> BuildBounceGraph();

// A small graph exercising the catalog types BuildBounceGraph doesn't:
// GetPosition, Sub, Div, CompareLe/CompareGt/CompareEq/CompareNeq, and
// CallFunction. Not run (CallFunction's target function isn't
// generated by GS9 -- see node_catalog.h's own comment on why that's a
// deliberate v1 limit) -- only its GENERATED TEXT is diffed against a
// committed .expected .cel fixture, proving codegen shape/determinism
// for the operators BuildBounceGraph doesn't reach.
std::unique_ptr<ce::node_system::Graph> BuildOperatorCoverageGraph();

// GS11: a SubgraphEntry named "Helper" (increments a global "counter"
// variable) called TWICE from on_start via two separate CallSubgraph
// nodes, then on_start reads the final counter into the entity's
// position -- both the flagship claim ("a subgraph called twice emits
// one func + two call sites") and real behavioral proof (final position
// (2,0,0) only if Helper genuinely ran twice, not zero or one times).
std::unique_ptr<ce::node_system::Graph> BuildSubgraphGraph();

// GS11: OnStart -> CallFunction("NonexistentHelper") -- generates
// cleanly (CallFunction trusts its target name, unlike CallSubgraph --
// see node_catalog.h's own comment), but fails ce::lang::AnalyzeProgram
// with UndefinedFunction. Exists to prove CheckGeneratedSource maps
// that sema-only failure back to the CallFunction node's id, not just
// an opaque source line nobody authoring the GRAPH ever saw.
std::unique_ptr<ce::node_system::Graph> BuildDiagnosticMappingGraph();

// GS11: the smallest possible graph with an observable trace --
// OnStart -> Log("trace demo"). With --trace, exactly one
// "trace node <id>" line (for the Log node -- OnStart itself is the
// entry, never itself passed through the exec-chain walk that emits
// trace calls) precedes the Log's own "[cel] trace demo" output.
std::unique_ptr<ce::node_system::Graph> BuildTraceDemoGraph();

} // namespace ce::lang::tools
